export const categories: { value: string }[] = [
  { value: 'antiques' },
  { value: 'appliances' },
  { value: 'arts+crafts' },
  { value: 'atv/utv/sno' },
  { value: 'auto parts' },
  { value: 'aviation' },
  { value: 'baby+kid' },
  { value: 'barter' },
  { value: 'beauty+hlth' },
  { value: 'bike parts' },
  { value: 'bikes' },
  { value: 'boat parts' },
  { value: 'boats' },
  { value: 'books' },
  { value: 'business' },
  { value: 'cars+trucks' },
  { value: 'cds/dvd/vhs' },
  { value: 'cell phones' },
  { value: 'clothes+acc' },
  { value: 'collectibles' },
  { value: 'computer parts' },
  { value: 'computers' },
  { value: 'electronics' },
  { value: 'farm+garden' },
  { value: 'free' },
  { value: 'furniture' },
  { value: 'garage sale' },
  { value: 'general' },
  { value: 'heavy equip' },
  { value: 'household' },
  { value: 'jewelry' },
  { value: 'materials' },
  { value: 'motorcycle parts' },
  { value: 'motorcycles' },
  { value: 'music instr' },
  { value: 'photo+video' },
  { value: 'rvs+camp' },
  { value: 'sporting' },
  { value: 'tickets' },
  { value: 'tools' },
  { value: 'toys+games' },
  { value: 'trailers' },
  { value: 'video gaming' },
  { value: 'wanted' },
  { value: 'wheels+tires' },
];
