export const categories: { value: string }[] = [
  { value: 'appliances' },
  { value: 'aviation' },
  { value: 'arts+crafts' },
  { value: 'baby+kid' },
  { value: 'beauty+hlth' },
  { value: 'bike' },
  { value: 'books' },
  { value: 'boat' },
  { value: 'car' },
  { value: 'computer parts' },
  { value: 'computers' },
  { value: 'electronics' },
  { value: 'farm+garden' },
  { value: 'free' },
  { value: 'household' },
  { value: 'jewelry' },
  { value: 'materials' },
  { value: 'music instr' },
  { value: 'other+misc' },
  { value: 'photo+video' },
  { value: 'sporting' },
  { value: 'tickets' },
  { value: 'tools' },
  { value: 'toys+games' },
  { value: 'video gaming' },
  { value: 'wanted' },
];
